-- Generated by nwg-displays on 2026-06-15 at 17:28:33. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@59.95",
    position = "4031x1079",
    scale = 1.0
})
hl.monitor({
    output = "DP-2",
    mode = "3840x2160@30.0",
    position = "191x728",
    scale = 1.0
})
