-- Generated by nwg-displays on 2026-07-08 at 09:09:25. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@59.95",
    position = "1242x2172",
    scale = 1.0
})
hl.monitor({
    output = "DP-2",
    mode = "3440x1440@59.97",
    position = "517x732",
    scale = 1.0
})
