-- Generated by nwg-displays on 2026-07-13 at 15:28:55. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@59.95",
    position = "1923x2041",
    scale = 1.0
})
hl.monitor({
    output = "DP-2",
    mode = "3440x1440@59.97",
    position = "1198x601",
    scale = 1.0
})
