return {
  -- {
  --   "akinsho/bufferline.nvim",
  --   version = "*",
  --   dependencies = "nvim-tree/nvim-web-devicons",
  --   config = function()
  --     vim.opt.termguicolors = true
  --
  --     local bufferline = require "bufferline"
  --
  --     bufferline.setup {
  --       options = {
  --         diagnostics = "nvim_lsp",
  --         -- rest of config ...
  --
  --         --- count is an integer representing total count of errors
  --         --- level is a string "error" | "warning"
  --         --- diagnostics_dict is a dictionary from error level ("error", "warning" or "info")to number of errors for each level.
  --         --- this should return a string
  --         --- Don't get too fancy as this function will be executed a lot
  --         diagnostics_indicator = function(count, level, diagnostics_dict, context)
  --           local s = " "
  --           for e, n in pairs(diagnostics_dict) do
  --             local sym = e == "error" and " " or (e == "warning" and " " or " ")
  --             s = s .. n .. sym
  --           end
  --           return s
  --         end,
  --         hover = {
  --           enabled = true,
  --           delay = 200,
  --           reveal = { "close" },
  --         },
  --       },
  --     }
  --
  --     vim.keymap.set("n", "<A-,>", function()
  --       bufferline.cycle(-1)
  --     end, { desc = "Previous Buffer" })
  --     vim.keymap.set("n", "<A-.>", function()
  --       bufferline.cycle(1)
  --     end, { desc = "Next Buffer" })
  --
  --     vim.keymap.set("n", "<A-c>", function()
  --       bufferline.close()
  --     end, { desc = "Close Buffer" })
  --
  --     vim.keymap.set("n", "<leader>bc", function()
  --       bufferline.close_others()
  --     end, { desc = "Close All But Current Buffer" })
  --   end,
  -- },
}
